### PR TITLE
Custom scrollbars and cleanup

### PR DESCRIPTION
**Pull request by bryvin**
Went through all the css and converted to flex. This allows for custom scrollbars to be used and still maintain all the correct positioning of hover items and the selected tag background.

This also allowed for the root container to be 100% height which means the horizontal scrollbar is now positioned properly at the bottom of the window.

This also still maintains the scrollbars in view only on hover of this component.

**Uses Stylekit style for scrollbar**
new-scrollbars-3

**Horizontal scroll at bottom of window**
new-scrollbars-2

### CODE REVIEW

**Comment by atmoio** [comment]
Issues:

- Unable to rename very nested tag because hover menu overlays. Perhaps a menu under the selected tag would solve this?
- Unable to scroll vertically/horizontally in Firefox on Mac and Windows.

**Comment by bryvin** [comment]
I think I found another issue.. if you have a severely nested set of tags you can have some issues with the digest because it's happening more than 10 times or something, I believe this effects the production version as well.


screenshot from 2018-11-16 19-04-53



This component though.. I'm so close to trying to rewrite it entirely.

**Comment by bryvin** [comment]
Some other issues with having the menu under the selected tag when it's selected is you can have multiple selected at a time.. then what?

**Comment by bryvin** [comment]
Think I may have an acceptable solution here. Check it out when you get a chance.

**Hovered**
screenshot from 2018-11-16 23-23-19
**Non hover**
screenshot from 2018-11-16 23-23-56

**Comment by atmoio** [comment]
This looks pretty good. The only thing is the "Add" button—not sure if there's a better name for that. Not clear what it does. A + icon would seem to make more sense. Or maybe "Nest". Not sure. Regarding the digest issue somewhere else, I've seen this issue before and it is fixable. I don't remember the solution but it might have been something to do with ng-repeat and trackBy.

**Comment by atmoio** [comment]
Some notes:

- Hovering over tags seems to have no visual cue anymore
- I find that when I click a tag with my cursor perfectly centered on it, the "Delete" option becomes immediately the next thing to gain focus and turns red. Almost scary. I kind of miss the +/- buttons. They looked visually nice. What was wrong with having them to the right of the selected tag again? It's ok if user has to scroll.

**Comment by bryvin** [comment]
Oh, I did seemingly break the hover effect.. my bad; I will re-add that for sure.

The thing with the action menu to the right of the tag/folder was it would always cover the content of the tag and sometimes even make it impossible to then edit the tag (as you need to click on the text for it to start editing). This can be fixed if it were just placed directly right always, but this does actually cause one more issue.. If the folder name is already near the end of the width (like you already almost have to scroll to see the full name of the tag) then when you hover over it it would push the width of the container even bigger.. meaning you would have to scroll even more to see the action menu. However you cannot because as soon as you hover away to go and scroll horizontally to the right more the action menu disappears and the width of the container shrinks meaning you cannot scroll over.

I am not sure on the correct fix for this entire thing, but certainly let me know how you'd like it to operate and I will give it a go.

**Comment by bryvin** [comment]
Transitioned back to original buttons as discussed. These always appear directly right of the end of the tag text. 10px over (so it's not right aligned to the container as it was before). This means you have to scroll to use the buttons if they're out of view, possibly confusing but if they know about it shouldn't be an issue. I also made it so you have to hover over to see the buttons just as it was originally to give it the clean look.

This keeps the dynamic of using flexbox and having the horizontal scrollbar at the bottom of the entire container and not just after the last tag. Hover scrollbars still remain for Chrome and browsers that support that type. Otherwise it reverts to the regular scrollbars; always visible if required.

This also seems to fix the issue (at least in my testing) with dragging folders down and up to nest them into other folders; seen in this issue: https://github.com/standardnotes/forum/issues/374

Let me know if there is anything else you see that needs to be corrected.

*This image was using inspected element and forcing the state to hover so I could take the picture to show end result.
scroll

**Comment by atmoio** [comment]
Some issues:

- Edit state on windows desktop cuts off:
normal
edit-state

- Themed scrollbars don't appear on Windows desktop.

- -/+ buttons are squished together, needs some horizontal spacing.

- When you edit a tag in Mac web app, the input is shifted down a few pixels. When you're done editing, it shifts back up.

So close..

**Comment by bryvin** [comment]
Oh nice 😄

I'll take a look today and submit some updates... interesting that it works on Linux but not Windows for the custom styles.

**Pull request merged**
